services:
  #booking-db:
    #image: postgres:latest
    #environment:
      # by default, username = postgres 
      #- POSTGRES_PASSWORD=SuperSecret7!
    #ports:
      #- 5432:5432
      
  booking-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - booking-db:/var/opt/mssql   
  
  saga-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - saga-db:/var/opt/mssql
  
  mongo-db:
    image : mongodb/mongodb-community-server:7.0.5-ubuntu2204
    ports:
      - "27017:27017"
        
volumes:
  booking-db:
  saga-db:
  mongo-db:    

