services:
  #booking-db:
    #image: postgres:latest
    #environment:
      # by default, username = postgres 
      #- POSTGRES_PASSWORD=SuperSecret7!
    #ports:
      #- 5432:5432
  
  booking-service:
    build:
      context: .
      dockerfile: AirlinesBookingSystem/Dockerfile
    env_file:
      - .env
    environment:
      - ConnectionString=${BOOKING_DB_CONNECTION}
      - Redis__ConnectionString=${REDIS_CONNECTION}
      - MongoDB__ConnectionString=${MONGO_CONNECTION}
      - MessageClientOptions__ConnectionString=${RABBITMQ_CONNECTION}

    depends_on:
      - booking-db
      - redis
      - mongo-db
    ports:
      - "8080:8080"
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-1
    ports:
      - "5672:5672"
      - "15672:15672"
  
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
        
  
  booking-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - booking-db:/var/opt/mssql   
  
  saga-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - saga-db:/var/opt/mssql
  
  
  payment-db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    ports:
      - "1435:1433"
    volumes:
      - payment-db:/var/opt/mssql
        
  
  mongo-db:
    image : mongodb/mongodb-community-server:7.0.5-ubuntu2204
    ports:
      - "27017:27017"
        
volumes:
  booking-db:
  saga-db:
  payment-db:
  mongo-db:    
  rabbit-mq:

